import {Component, Input, OnInit} from '@angular/core';
import * as pdfMake from 'pdfmake/build/pdfmake.js';
import * as pdfFonts from 'pdfmake/build/vfs_fonts.js';

// @ts-ignore
pdfMake.vfs = pdfFonts.pdfMake.vfs;
@Component({
  selector: 'app-signchart',
  templateUrl: './signchart.component.html',
  styleUrls: ['./signchart.component.scss']
})
export class SignchartComponent implements OnInit{
  ngOnInit(): void {}

  public export(): void {
    var docDefinition =
      {
        content: [

          {
            table: {
              widths: ['auto', 38, 37, 38, 37, 37, 'auto', 'auto',  38,  37,  38,  37, 37],
              heights: ['auto', 'auto', 'auto', 'auto', 'auto',
                'auto', 'auto', 'auto', 'auto', 31,
                31, 31, 31, 31, 31,
                31, 31, 31, 31, 31,
                31, 31, 31, 31, 31,
                'auto'],

              //headerRows: 2,
              // keepWithHeaderRows: 1,
              body: [
                [  //1
                  {text: 'pHOTO', style: 'header', colSpan:2,rowSpan:5, alignment: 'center'},
                  {},
                  {text: '\n\n\nKISMI ZAMANLI ÇALIŞAN ÖĞRENCİLERİN SAATLİK İMZA ÇİZELGESİ', style: 'header',colSpan:8,rowSpan:5, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'Doküman No:', style: 'header2',colSpan:2, alignment: 'left'},
                  {},
                  {},

                ],
                [   //2
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'Yayın Tarihi:', style: 'header2',colSpan:2, alignment: 'left'},
                  {},
                  {},
                ],
                [//3
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'Revizyon Tarihi:', style: 'header2',colSpan:2, alignment: 'left'},
                  {},
                  {},

                ],
                [//4
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'Revizyon No:', style: 'header2',colSpan:2, alignment: 'left'},
                  {},
                  {},
                ],
                [//5
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'Sayfa No:', style: 'header2',colSpan:2, alignment: 'left'},
                  {},
                  {},
                ],
                [//6
                  {text: 'Birimi', style: 'header',colSpan:6, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '', style: 'header',rowSpan:21, alignment: 'center'},
                  {text: 'Adı Soyadı', style: 'header',colSpan:6, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//7
                  {text: 'Nisan', style: 'header',colSpan:5, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {text: '2024', style: 'header', alignment: 'center'},
                  {},
                  {text: '', style: 'header',colSpan:6, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//8
                  {text: 'ÇALIŞMA SAATLERİ', style: 'header',colSpan:6, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'ÇALIŞMA SAATLERİ', style: 'header',colSpan:6, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//9
                  {text: 'Gün', style: 'texter', alignment: 'center'},
                  {text: 'GİRİŞ SAATİ', style: 'texter', alignment: 'center'},
                  {text: 'İMZA', style: 'texter', alignment: 'center'},
                  {text: 'ÇIKIŞ SAATİ', style: 'texter', alignment: 'center'},
                  {text: 'İMZA', style: 'texter', alignment: 'center'},
                  {text: 'GÜNLÜK TOPLAM ÇALIŞMA SAATİ', style: 'texter', alignment: 'center'},
                  {},
                  {text: 'Gün', style: 'texter', alignment: 'center'},
                  {text: 'GİRİŞ SAATİ', style: 'texter', alignment: 'center'},
                  {text: 'İMZA', style: 'texter', alignment: 'center'},
                  {text: 'ÇIKIŞ SAATİ', style: 'texter', alignment: 'center'},
                  {text: 'İMZA', style: 'texter', alignment: 'center'},
                  {text: 'GÜNLÜK TOPLAM ÇALIŞMA SAATİ', style: 'texter', alignment: 'center'},
                ],
                [//10
                  {text: '1', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '17', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//11
                  {text: '2', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '18', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//12
                  {text: '3', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '19', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//13
                  {text: '4', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '20', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                ],
                [//14
                  {text: '5', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {},
                  {text: '21', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                ],
                [//15
                  {text: '6', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {},
                  {text: '22', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//16
                  {text: '7', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '23', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//17
                  {text: '8', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '24', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//18
                  {text: '9', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '25', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//19
                  {text: '10', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '26', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//20
                  {text: '11', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '27', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                ],
                [//21
                  {text: '12', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '28', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                ],
                [//22
                  {text: '13', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {},
                  {text: '29', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//23
                  {text: '14', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {},
                  {text: '30', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//24
                  {text: '15', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: '31', style: 'texter', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                  {text: '', style: 'tableblack',fillColor: '#000000', alignment: 'center'},
                ],
                [//25
                  {text: '16', style: 'texter', alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {text: 'TOPLAM ÇALIŞMA SAATİ:', style: 'header', colSpan: 6, alignment: 'left'},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],
                [//26
                  {text: 'DÜZENLEYEN VE KONTROL EDEN BİRİMİ AMİRİ: İMZA/TARİH/KAŞE', style: 'textfoot',colSpan: 13, alignment: 'center'},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                  {},
                ],

              ]
            }
          },

        ],
        styles: {
          header: {
            fontSize: 8,
            bold: true
          },
          header2: {
            fontSize: 8,
            bold: false,

          },
          texter:{
            fontSize: 6,
            bold: false
          },
          textfoot:{
            fontSize: 9,
            bold: false
          },
          tableblack:{
            background: 'black'
          }

        }
      };

    // @ts-ignore
    pdfMake.createPdf(docDefinition).download("test.pdf");
  }

}
